# Site settings
title: Learning By Teaching － A blog about my learning path.
email: learningbyteaching.jimmy@gmail.com
description: 我一直觉得学习任何东西，最好的方法就是将你学到的东西教一遍。现在我正在学习各种设计类的软件，所以我想将我学到的东西写下来，po到这个博客。供大家学习。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://questionhunt.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title
